# functions and putting together things we learnt in last few weeks

** Important elements of a function 
** 1) Name 2) parameters (or arguments) 3) logic 4) output value(s)

In [1]:
# function to add two numbers
def addTwoNumbers(x,y):
    c=x+y
    return c

In [2]:
z=addTwoNumbers(333,77)
z

410

In [4]:
x=333
y=77
c=x+y
c

410

In [5]:
x

333

In [6]:
# function to add two numbers
def addTwoNumbersV2(x,y):
    return x+y
    

In [7]:
z=addTwoNumbers(333,77)
z

410

In [15]:
# I want to perform 4 math functions, 1, I would like to add two number
def fourMathFunctions(x,y,typ):
    if typ=='1':
        c=x+y
    elif typ=='2':
        c=x-y
    elif typ=='3':
        c=x*y
    elif typ=='4':
        c=x/y
    else:
        c="Enter the right value dummy!"
    return c

In [16]:
print (fourMathFunctions(10,20,typ='5'))

Enter the right value dummy!


In [35]:
import pandas as pd
import numpy as np
a=2
b=[1,2,3]
c=np.array([1,2,3])
d=pd.DataFrame([1,2,3])


In [26]:
type(d)

pandas.core.frame.DataFrame

In [27]:
type(a)

int

In [49]:
# The goal is convert whatever you pass as argument into an numpy array
# Input parameters -variable (int, list, numpy, pandas)
# Output we are expecting is numpy array
# Logic first I need to know what data types the input parameter is 
def convertToNumpy(x):
    if type(x)==int:
        c=np.array(x)
    elif type(x)==list:
        c=np.array(x)
    elif type(x)==pd.core.frame.DataFrame:
        c=d.values
    else:
        c=x
    return c

In [28]:
type(c)

numpy.ndarray

In [30]:
np.array(b)

array([1, 2, 3])

In [32]:
d.values

array([[1],
       [2],
       [3]])

In [51]:
convertToNumpy(c)

array([1, 2, 3])

In [179]:
import os
path ='https://raw.githubusercontent.com/vikrambj2019/basic/master/Data/'
filename_read=os.path.join(path,"twobytwo.csv")
df=pd.read_csv(filename_read,na_values=['NA','?'])

In [161]:
df.head()

C1   C2   C3   C4
0  3.0  4.0  1.0  NaN
1  NaN  2.0  NaN  NaN
2  NaN  NaN  2.0  NaN
3  NaN  1.0  4.0  3.0

In [55]:
ls=df.values

In [59]:
ls

array([[3., 4., 1., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [57]:
np.argwhere(np.isnan(ls))

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]])

In [58]:
ls[np.isnan(ls)]=0

In [61]:
a=np.argwhere(ls==0)

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]])

In [64]:
ls[0]

array([0., 2., 0., 0.])

In [67]:
ls[:,3]

array([4., 2., 0., 1.])

In [68]:
ls[0:2,2:4]

array([[1., 0.],
       [0., 0.]])

In [87]:
row=a[0][0]
col=a[0][1]


In [72]:
a=np.argwhere(ls==0)

In [75]:
a[0][1]

3

In [82]:
if a[0][0] in (0,1):
    row_sq=0
else:
    row_sq=2
row_sq

0

In [83]:
if a[0][1] in (0,1):
    col_sq=0
else:
    col_sq=2
col_sq

2

In [84]:
ls[row_sq:row_sq+2,col_sq:col_sq+2]

array([[1., 0.],
       [0., 0.]])

In [85]:
ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4)

array([[1., 0., 0., 0.]])

In [88]:
row

0

In [90]:
ls[row]

array([0., 0., 2., 0.])

In [98]:
a=np.append(ls[row].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist(),ls[:,col].tolist()])

In [99]:
a

array([3., 4., 1., 0., 1., 0., 0., 0., 0., 0., 0., 3.])

In [117]:
list1=[1,2,3,4,0]
b=set(list1).difference(a)
b

{2}

In [141]:
ls=df.values# Convert pandas to numpy array
ls[np.isnan(ls)]=0 # Convert null to zeros
a=np.argwhere(ls==0) # Saving the adress location of all zeros in array called "a"

row=a[0][0] # Will give me the row of first zero address 
col=a[0][1] # Will give me the col of the first zero address
ls[row] # will give me the array of the row
ls[:,col] # This will give me the columns values 
if a[0][0] in (0,1):
    row_sq=0
else:
    row_sq=2

if a[0][1] in (0,1):
    col_sq=0
else:
    col_sq=2

ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten()
a=np.append(ls[row].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist(),ls[:,col].tolist()])
list1=[1,2,3,4,0]
b=set(list1).difference(a)
ls[row,col]=list(b)[0]


In [112]:
set(a)

{0.0, 1.0, 3.0, 4.0}

In [133]:
list

[]

In [142]:
ls

array([[3., 4., 1., 2.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [107]:
a[0][0]

0

In [138]:
del list

In [139]:
list(b)

[2]

In [140]:
ls[row,col]

0.0

In [192]:
def sudokuTwoByTwoStrategy1(df):
    ls=df.values# Convert pandas to numpy array
    ls[np.isnan(ls)]=0 # Convert null to zeros
    a=np.argwhere(ls==0) # Saving the adress location of all zeros in array called "a"
    for i in range(len(a)):
        b=a[i]
        row=b[0] # Will give me the row of first zero address 
        col=b[1] # Will give me the col of the first zero address
        #ls[row] # will give me the array of the row
        #ls[:,col] # This will give me the columns values 
        if row in (0,1):
            row_sq=0
        else:
            row_sq=2

        if col in (0,1):
            col_sq=0
        else:
            col_sq=2

        #ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten()
        c=np.append(ls[row].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).flatten().tolist(),ls[:,col].tolist()])
        list1=[1,2,3,4,0]
        d=set(list1).difference(c)
        if len(d)==1:
            ls[row,col]=list(d)[0]
            
    return ls

In [193]:
ls=sudokuTwoByTwoStrategy1(df)

In [194]:
ls


array([[3., 4., 1., 2.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.],
       [2., 1., 4., 3.]])