In [272]:
#We will use this section to load all libraries
import os
import pandas as pd
import numpy as np

In [294]:
# Read CSV
#print(os.listdir("../Vikram Bandugula"))
path='C:/Users/Vikram.Bandugula/Downloads/'
filename_read = os.path.join(path,"twobytwo.csv")

df = pd.read_csv(filename_read,na_values=['NA','?'])

In [295]:
df

C1   C2   C3   C4
0  3.0  4.0  1.0  NaN
1  NaN  2.0  NaN  NaN
2  NaN  NaN  2.0  NaN
3  NaN  1.0  4.0  3.0

In [188]:
ls=df.values

In [189]:
np.argwhere(np.isnan(ls))
#np.argwhere(ls)

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [190]:
ls[np.isnan(ls)] = 0 

In [191]:
ls

array([[3., 4., 1., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [192]:
np.argwhere(ls==0)

array([[0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [38]:
ls

array([[3., 4., 1., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 1., 4., 3.]])

In [59]:
a=np.append(ls[0:1,:].tolist(),[ls[0:2,2:4].reshape(1,4).tolist(),ls[:,3:4].reshape(1,4).tolist()])

In [100]:
list2=[1,2,3,4,0]
b=set(list2).difference(a)

In [104]:
len(list(b))

1

In [106]:
def add_vb(a,b):
    return a+b


In [107]:
c=add_vb(2,3)
c

5

In [122]:
def four_mathfun(a,b,typ):
    if typ=='1':
        c=a+b
    elif typ=='2':
        c=a-b
    elif typ=='3':
        c-a*b
    else:
        c=a/b
    
    return c

In [125]:
c=four_mathfun(4,5,typ='1')
c

9

In [126]:
def add_vb_1(a,b):
    return a,b,a+b

In [128]:
a,b,c=add_vb_1(3,4)
print(f"sum of {a} and {b} is {c}")

sum of 3 and 4 is 7


** What are involved in function
** Name of fuction, 
** parameters or arguments
** What it will return ,
** It needs the logic

In [277]:
#a=np.append(ls[0:1,:].tolist(),[ls[0:2,2:4].reshape(1,4).tolist(),ls[:,3:4].reshape(1,4).tolist()])
a=np.argwhere(ls==0)
len(a)

7

In [195]:
a[0]

array([0, 3], dtype=int64)

In [166]:
row=a[0,0]
col=a[0,1]

In [167]:
ls[row,:]

array([3., 4., 1., 0.])

In [168]:
ls[:,col:].reshape(1,4)

array([[0., 0., 0., 3.]])

In [169]:
if row in (0,1):
    row_sq=0
else:
    row_sq=2

In [170]:
if col in (0,1):
    col_sq=0
else:
    col_sq=2

In [171]:
ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4)

array([[1., 0., 0., 0.]])

In [173]:
a=np.append(ls[row,:].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).tolist(),ls[:,col:].reshape(1,4).tolist()])

In [174]:
a

array([3., 4., 1., 0., 1., 0., 0., 0., 0., 0., 0., 3.])

In [175]:
list2=[1,2,3,4,0]
b=set(list2).difference(a)
b

{2}

In [182]:
ls[row,col]=list(b)[0]

In [268]:
ls

array([[3., 4., 1., 2.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.],
       [2., 1., 4., 3.]])

In [298]:
def updateValuesStrategyOne(df):
    ls=df.values
    ls[np.isnan(ls)] = 0 
    a=np.argwhere(ls==0)
    #if len(a)==0:
     #   print ("Completed the puzzle")
      #  return ls
    #else:
    for i in range(len(a)):   
        b=a[i]
        row=b[0]
        col=b[1]
        if row in (0,1):
            row_sq=0
        else:
            row_sq=2
        if col in (0,1):
            col_sq=0
        else:
            col_sq=2
        c=np.append(ls[row,:].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).tolist(),ls[0:,col:col+1].reshape(1,4).tolist()])
        list2=[1,2,3,4,0]
        d=set(list2).difference(c)
        if len(d)==1:
            ls[row,col]=list(d)[0]
    if np.argwhere(ls==0).size>0:
        print ("Puzzle is not complete")
    else:
        print("Puzzle is complete")
    return ls

In [299]:
import time
start_time = time.time()
ls=updateValuesStrategyOne(df)
print("--- %s seconds ---" % (time.time() - start_time))

Puzzle is complete
--- 0.0 seconds ---


In [300]:
ls

array([[3., 4., 1., 2.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.],
       [2., 1., 4., 3.]])

In [279]:
    ls=df.values
    ls[np.isnan(ls)] = 0 
    a=np.argwhere(ls==0)
    for i in range(len(a)):
        b=a[i]
        row=b[0]
        col=b[1]
        if row in (0,1):
            row_sq=0
        else:
            row_sq=2
        if col in (0,1):
            col_sq=0
        else:
            col_sq=2
        c=np.append(ls[row,:].tolist(),[ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4).tolist(),ls[0:,col:col+1].reshape(1,4).tolist()])
        list2=[1,2,3,4,0]
        d=set(list2).difference(c)
        ls[row,col]=list(d)[0]

In [243]:
a

array([[1, 0],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0]], dtype=int64)

In [221]:
b

array([1, 0], dtype=int64)

In [244]:
d

{1}

In [222]:
row

1

In [223]:
col

0

In [224]:
row_sq

0

In [225]:
col_sq

0

In [228]:
ls[row_sq:row_sq+2,col_sq:col_sq+2].reshape(1,4)

array([[3., 4., 0., 2.]])

In [229]:
ls[row,:]

array([0., 2., 0., 0.])

In [236]:
ls[0:,col:col+1]

array([[3.],
       [0.],
       [0.],
       [0.]])

In [240]:
ls[0:,2:]

array([[1., 2.],
       [0., 0.],
       [2., 0.],
       [4., 3.]])

In [261]:
a=np.argwhere(ls==0)

In [262]:
len(a)

0

In [269]:
pd.DataFrame(ls).to_csv(os.path.join(path,"twobytwoout.csv"))

In [291]:
np.argwhere(ls==0).size

0