# Week 3, Class 5- 
** Storing data
* Pandas, List, array's 
** What is difference between list and array.

In [2]:
list_q=['a',1]
list_q

['a', 1]

In [4]:
list_q=[['a',1],['b',2]]
list_q 

[['a', 1], ['b', 2]]

In [13]:
import numpy as np
import sys
b=np.array([1,2,3])
b

array([1, 2, 3])

In [8]:
b.dtype

dtype('int32')

In [11]:
print(b/3)

[0.33333333 0.66666667 1.        ]


In [12]:
list_2=[1,2,3]
print(list_2/3)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

NumPy arrays are made to be created as homogeneous arrays, 
considering the mathematical operations that can be performed on them. 
It would not be possible with heterogeneous data sets.


In [14]:
py_arr = [1,2,3,4,5,6]
numpy_arr = np.array([1,2,3,4,5,6])


In [16]:
sizeof_py_arr = sys.getsizeof(1) * len(py_arr)
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size
print(f"Size of list is {sizeof_py_arr} and size of array is {sizeof_numpy_arr}")

Size of list is 168 and size of array is 24


In [17]:
# Set predefined array
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [22]:
a= np.arange(0,10,0.5).reshape(10,2)
a

array([[0. , 0.5],
       [1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [24]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
a = np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it

In [26]:
py_arr = [1,2,3] * 2
py_arr

[1, 2, 3, 1, 2, 3]

In [27]:
a=np.array([1,2,3]) * 2
a

array([2, 4, 6])

In [28]:
a=np.array([1,2,3]) + 2
a

array([3, 4, 5])

In [30]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c= a * b
c

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
c=a+b
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
np.sqrt(c)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162]])

In [33]:
np.mean(c)

7.0

In [34]:
np.sum(c)

42

In [35]:
np.min(c)

2

In [36]:
np.max(c)

12

4. Finding Elements in NumPy array

In [37]:
a=np.array([1,2,0,4,5])
np.where(a > 2)

(array([3, 4], dtype=int64),)

In [38]:
np.nonzero(a)

(array([0, 1, 3, 4], dtype=int64),)

In [41]:
np.count_nonzero(a)

4

In [42]:
np.where(a==0)

(array([2], dtype=int64),)

In [43]:
a[1]

2

In [45]:
b=[[1,3],[2,5],[3,7]]

In [52]:
b[0:3]

[[1, 3], [2, 5], [3, 7]]

In [54]:
a = np.zeros((5,2))
a.fill(100)
a

array([[100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.]])

2. Slicing NumPy Arrays
The : is called the separator and works with Inclusive — Exclusive principal, which means that the left of the separator shall be included while right of the separator will be excluded.

In [55]:
a = np.array([1,2,3,4,5,6])

In [57]:
a[:] 

array([1, 2, 3, 4, 5, 6])

In [58]:
a[0:2]

array([1, 2])

In [59]:
a[1:4]

array([2, 3, 4])

In [60]:
a[0:]

array([1, 2, 3, 4, 5, 6])

In [62]:
a[:4]

array([1, 2, 3, 4])

In [64]:
a[:] = 100
a

array([100, 100, 100, 100, 100, 100])

In [66]:
a[1:4]=200 
a

array([100, 200, 200, 200, 100, 100])

[rows → Start_Index : End_Index, Column → Start_Index : End_Index ]

In [67]:
a = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9]])

In [68]:
a[:] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a[:,1] 

array([2, 5, 8])

In [72]:
a = np.array([ [[1,1], [2,2], [3,3]],
                    [[4,4], [5,5] ,[6,6]],
                    [[7,7], [8,8], [9,9]]
                ])

In [73]:
a[:,:,0] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

3. Splitting the NumPy Arrays

In [77]:
a = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
             [1,1,1,1]])

In [78]:
#Split Row Wise
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [ 1,  1,  1,  1]])]

In [79]:
#Split Column Wise
np.hsplit(a,4)

[array([[1],
        [5],
        [9],
        [1]]), array([[ 2],
        [ 6],
        [10],
        [ 1]]), array([[ 3],
        [ 7],
        [11],
        [ 1]]), array([[ 4],
        [ 8],
        [12],
        [ 1]])]

In [80]:
a=[1,2,3,4]

In [81]:
a.append(5)

In [82]:
a

[1, 2, 3, 4, 5]

In [84]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a*b
c

array([ 4, 10, 18])

In [86]:
c=np.dot(a,b)
c

32

In [87]:
np.matmul(a, b)

32

In [88]:
a

array([1, 2, 3])

In [89]:
a[(a>6) & (a<10)]

array([], dtype=int32)

In [92]:
l = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
a = np.array(l, dtype='float')
a

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [93]:
a[1,1] = np.nan  # not a number
a

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [94]:
a[1,2] = np.inf  # infinite
a

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [95]:
missing_bool = np.isnan(a) | np.isinf(a)
missing_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [97]:
a[missing_bool] = -1  
a

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [98]:
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [99]:
uniqs, counts = np.unique(arr_rand, return_counts=True)


In [100]:
print(f"Unique values are {uniqs}, count is {counts}")

Unique values are [0 2 3 4 5 7 8], count is [1 2 1 1 1 2 2]


In [104]:
a=[1,2,3,4,5]
b=[3,4]
np.setdiff1d(a,b)

array([1, 2, 5])